import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createAuth, totpCode } from "../server/auth.mjs";

const dataDir = await mkdtemp(join(tmpdir(), "goodkota-auth-test-"));
let clock = Date.UTC(2026,0,1);
const messages = [];
const sendVerification = async (email,token) => messages.push({email,token});
try {
  const auth = createAuth({dataDir,adminEmail:"office@example.test",adminPassword:"OfficePassword123!",now:() => clock,sendVerification});
  const customer = await auth.registerCustomer({email:"Customer@Example.test",password:"CustomerPassword123!",role:"admin",merchantId:"m1"});
  assert.deepEqual([customer.user.role,customer.user.emailVerified], ["customer",false]);
  assert.equal((await auth.fromToken(customer.token)).email, "customer@example.test");
  assert.equal(messages.length,1);
  await assert.rejects(() => auth.resendVerification(customer.user), /Too many/);
  clock += 61_000;
  await auth.resendVerification(customer.user);
  await assert.rejects(() => auth.verifyEmail(messages[0].token), /invalid or expired/);
  await auth.verifyEmail(messages[1].token);
  assert.equal((await auth.fromToken(customer.token)).emailVerified,true);
  await assert.rejects(() => auth.verifyEmail(messages[1].token), /invalid or expired/);
  await assert.rejects(() => auth.inviteMerchant(customer.user, "m1", "merchant@example.test"), /Not authorised/);
  await assert.rejects(() => auth.registerCustomer({email:"customer@example.test",password:"AnotherPassword123!"}), /already has/);
  await assert.rejects(() => auth.login("customer@example.test", "wrong", "test-ip"), /incorrect/);
  const pending = await auth.login("office@example.test", "OfficePassword123!", "test-ip");
  assert.equal(pending.next,"mfa_enroll");
  assert.equal(pending.token,undefined);
  const setup = await auth.mfaSetup(pending.challenge);
  assert.match(setup.uri,/otpauth:\/\/totp\/GoodKota/);
  await assert.rejects(() => auth.completeMfa(pending.challenge,"00000000"), /Incorrect code/);
  const admin = await auth.completeMfa(pending.challenge,totpCode(setup.secret,Math.floor(clock/30_000)));
  assert.equal(admin.user.role,"admin");
  assert.equal(admin.backupCodes.length,8);
  await assert.rejects(() => auth.completeMfa(pending.challenge,"000000"), /expired/);
  const invite = await auth.inviteMerchant(admin.user, "m1", "merchant@example.test");
  await assert.rejects(() => auth.claimMerchant({email:invite.email,code:"bad",password:"MerchantPassword123!"}), /invalid/);
  const merchant = await auth.claimMerchant({email:invite.email,code:invite.code,password:"MerchantPassword123!"});
  assert.deepEqual([merchant.user.role,merchant.user.merchantId,merchant.user.emailVerified], ["merchant","m1",false]);
  await assert.rejects(() => auth.claimMerchant({email:invite.email,code:invite.code,password:"MerchantPassword123!"}), /invalid/);
  clock += 24*60*60_000+1;
  await assert.rejects(() => auth.verifyEmail(messages[2].token), /invalid or expired/);
  await auth.resendVerification(merchant.user);
  await auth.verifyEmail(messages[3].token);
  auth.logout(merchant.token);
  assert.equal(await auth.fromToken(merchant.token), null);
  const file = join(dataDir, "accounts.json");
  const contents = await readFile(file, "utf8");
  assert(!contents.includes("MerchantPassword123!") && !contents.includes(invite.code) && !contents.includes(messages[3].token) && !contents.includes(admin.backupCodes[0]));
  assert.equal((await stat(file)).mode & 0o777, 0o600);
  const restarted = createAuth({dataDir,now:() => clock,sendVerification});
  assert.equal((await restarted.login("merchant@example.test", "MerchantPassword123!", "test-ip")).user.emailVerified,true);
  assert.equal(await restarted.fromToken(admin.token), null);
  const next = await restarted.login("office@example.test", "OfficePassword123!", "test-ip");
  assert.equal(next.next,"mfa_verify");
  const recovered = await restarted.completeMfa(next.challenge,admin.backupCodes[0]);
  assert.equal(recovered.user.role,"admin");
  const reuse = await restarted.login("office@example.test", "OfficePassword123!", "test-ip");
  await assert.rejects(() => restarted.completeMfa(reuse.challenge,admin.backupCodes[0]), /Incorrect code/);
  console.log("Verified email and admin MFA workflow passed.");
} finally {
  await rm(dataDir, {recursive:true,force:true});
}
