import assert from "node:assert/strict";
import { randomBytes } from "node:crypto";
import { mkdtemp, readFile, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createGoodKotaServer } from "../server/server.mjs";
import { totpCode } from "../server/auth.mjs";

const dataDir = await mkdtemp(join(tmpdir(), "goodkota-payfast-test-"));
const token = randomBytes(32).toString("hex");
const emails = [];
const readyEmails = [];
const server = createGoodKotaServer({authProvider:"local",token, encryptionKey:randomBytes(32).toString("base64"), dataDir, authDir:join(dataDir,"auth"),stateDir:join(dataDir,"state"),adminEmail:"office@example.test",adminPassword:"OfficePassword123!",sendVerification:async (to,code) => emails.push({to,code}),sendOrderReady:async message => readyEmails.push(message)});
await new Promise(resolve => server.listen(0, "127.0.0.1", resolve));
const base = `http://127.0.0.1:${server.address().port}`;
const login = await fetch(`${base}/api/auth/login`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:"office@example.test",password:"OfficePassword123!"})});
assert.equal(login.status, 202);
const pendingCookie = login.headers.get("set-cookie").match(/goodkota_mfa=[^;]+/)[0];
const setup = await (await fetch(`${base}/api/auth/mfa/setup`,{headers:{Cookie:pendingCookie}})).json();
assert(setup.secret);
assert.equal((await (await fetch(`${base}/api/auth/session`,{headers:{Cookie:pendingCookie}})).json()).user,null);
const complete = await fetch(`${base}/api/auth/mfa/complete`,{method:"POST",headers:{Cookie:pendingCookie,"Content-Type":"application/json"},body:JSON.stringify({code:totpCode(setup.secret,Math.floor(Date.now()/30_000))})});
assert.equal(complete.status,200);
const auth = {Authorization:`Bearer ${token}`,Cookie:complete.headers.get("set-cookie").match(/__session=[^;]+/)[0]};

try {
  assert.match(complete.headers.get("set-cookie"), /HttpOnly; SameSite=Strict/);
  assert.equal((await (await fetch(`${base}/api/auth/session`,{headers:{Cookie:auth.Cookie}})).json()).user.role, "admin");
  const inviteResponse = await fetch(`${base}/api/auth/invite`, {method:"POST",headers:{Cookie:auth.Cookie,"Content-Type":"application/json"},body:JSON.stringify({merchantId:"m1",email:"merchant@example.test"})});
  assert.equal(inviteResponse.status, 201);
  const invite = await inviteResponse.json();
  const claimResponse = await fetch(`${base}/api/auth/claim`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:invite.email,code:invite.code,password:"MerchantPassword123!"})});
  assert.equal(claimResponse.status, 201);
  const merchantCookie = claimResponse.headers.get("set-cookie").split(";")[0];
  assert.equal((await claimResponse.json()).user.role, "merchant");
  assert.equal((await fetch(`${base}/api/actions`,{method:"POST",headers:{Cookie:merchantCookie,"Content-Type":"application/json"},body:JSON.stringify({type:"merchant_availability_changed",payload:{merchantId:"m1",online:false}})})).status,400);
  await fetch(`${base}/api/auth/verify-email`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:emails.at(-1).code})});
  assert.equal((await fetch(`${base}/api/admin/payfast/status?storeId=m1`,{headers:{Authorization:`Bearer ${token}`,Cookie:merchantCookie}})).status, 403);
  assert.equal((await fetch(`${base}/api/auth/invite`,{method:"POST",headers:{Cookie:merchantCookie,"Content-Type":"application/json"},body:"{}"})).status, 403);
  const guestData = await (await fetch(`${base}/api/data`)).json();
  assert.equal(guestData.state.role, "customer");
  assert.equal(guestData.state.orders.length, 0);
  assert(!guestData.state.merchants[0].payfast);
  const signup = await fetch(`${base}/api/auth/register`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:"customer@example.test",password:"CustomerPassword123!"})});
  assert.equal(signup.status, 201);
  const customerCookie = signup.headers.get("set-cookie").split(";")[0];
  await fetch(`${base}/api/auth/verify-email`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:emails.at(-1).code})});
  const orderResponse = await fetch(`${base}/api/actions`,{method:"POST",headers:{Cookie:customerCookie,"Content-Type":"application/json"},body:JSON.stringify({type:"pickup_order_created",payload:{merchantId:"m1",requestId:"GK-0000000000000002",details:{firstName:"Nandi",lastName:"Dube",phone:"0111111111",email:"customer@example.test"},cart:[{productId:"p1",name:"Classic Kota",unitPrice:4800,qty:1,choices:[]}]}})});
  assert.equal(orderResponse.status, 200);
  const orderId = (await orderResponse.json()).state.orders[0].id;
  assert.equal((await (await fetch(`${base}/api/data`,{headers:{Cookie:merchantCookie}})).json()).state.orders[0].id,orderId);
  const accepted = await fetch(`${base}/api/actions`,{method:"POST",headers:{Cookie:merchantCookie,"Content-Type":"application/json"},body:JSON.stringify({type:"order_status_changed",payload:{orderId,status:"accepted"}})});
  assert.equal(accepted.status,200);
  const ready = await fetch(`${base}/api/actions`,{method:"POST",headers:{Cookie:merchantCookie,"Content-Type":"application/json"},body:JSON.stringify({type:"order_status_changed",payload:{orderId,status:"ready"}})});
  assert.equal(ready.status,200);
  assert.equal((await ready.json()).notificationDelivery.status,"sent","Ready transition should invoke transactional notification delivery");
  assert.equal(readyEmails.length,1);
  assert.deepEqual([readyEmails[0].to,readyEmails[0].orderId],["customer@example.test",orderId]);
  const customerAlerts = await (await fetch(`${base}/api/data`,{headers:{Cookie:customerCookie}})).json();
  assert.equal(customerAlerts.state.notifications[0].orderId,orderId,"Customer should retain the Ready alert in-app");
  assert.equal((await (await fetch(`${base}/api/data`)).json()).state.orders.length,0);
  const forged = await fetch(`${base}/api/actions`,{method:"POST",headers:{Cookie:customerCookie,"Content-Type":"application/json"},body:JSON.stringify({type:"merchant_availability_changed",payload:{merchantId:"m1",online:false}})});
  assert.equal(forged.status,400);
  assert.equal((await fetch(`${base}/api/admin/payfast/capabilities`)).status, 200);
  assert.equal((await fetch(`${base}/api/admin/payfast/status`)).status, 403);
  const status = await (await fetch(`${base}/api/admin/payfast/status?storeId=m1`, {headers:auth})).json();
  assert.equal(status.configured, false);
  const response = await fetch(`${base}/api/admin/payfast/config`, {method:"POST", headers:{...auth,"Content-Type":"application/json"}, body:JSON.stringify({storeId:"m1",environment:"sandbox",merchantId:"12345678",merchantKey:"secretKey123",passphrase:"a-sandbox-secret"})});
  assert.equal(response.status, 200);
  const saved = await (await fetch(`${base}/api/admin/payfast/status?storeId=m1`, {headers:auth})).json();
  assert.deepEqual([saved.configured, saved.merchantIdMasked, saved.checkoutActive], [true,"••••5678",false]);
  assert.equal(JSON.stringify(saved).includes("secretKey123"), false);
  assert.equal((await (await fetch(`${base}/api/admin/payfast/status?storeId=m2`, {headers:auth})).json()).configured, false);
  const filename = join(dataDir, "payfast-m1.enc.json");
  assert.equal((await readFile(filename, "utf8")).includes("secretKey123"), false);
  assert.equal((await stat(filename)).mode & 0o777, 0o600);
  assert.equal((await fetch(`${base}/api/admin/payfast/config`, {method:"POST", headers:{...auth,"Content-Type":"application/json",Origin:"https://other.example"}, body:"{}"})).status, 403);
  assert.equal((await fetch(`${base}/server/server.mjs`)).status, 404);
  assert.equal((await fetch(`${base}/index.html`)).status, 200);
  assert.equal((await fetch(`${base}/api/admin/payfast/config?storeId=m1`, {method:"DELETE",headers:auth})).status, 200);
  assert.equal((await (await fetch(`${base}/api/admin/payfast/status?storeId=m1`, {headers:auth})).json()).configured, false);
  console.log("Secure PayFast setup API passed.");
} finally {
  await new Promise(resolve => server.close(resolve));
  await rm(dataDir, {recursive:true, force:true});
}
